# Generated by Django 3.2 on 2023-01-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230127_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Код подтверждения'),
        ),
    ]
